import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import State from "@/app/Context/State";
import { Toaster } from "react-hot-toast";

const inter = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Sight Shark Portal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <State>
          <Toaster />
          {children}
        </State>
      </body>
    </html>
  );
}
